#!/usr/bin/python3

import main
import os

COMPUTER_NAME = __import__("platform").node()

PATH = ["bin"]
COMMAND_PREFIX = "# EMREX SHELL COMMAND\n"
PS = "[emrex@{computer_name} {current_dir}] λ " # TODO: Make ps more customizable.

COMMANDS = []
for path in PATH:
    files = os.listdir(path)
    for file in files:
        if file == "__pycache__": continue
        f = open(os.path.join(path, file), "r")
        if f.readline() == COMMAND_PREFIX:
            module_path = path.rstrip("/")+"." + file.rstrip(".py")
            COMMANDS.append(__import__(module_path, fromlist=[""]))
        else:
            print("WARNING: A non command file found in one of the path dirs.")
        f.close()

def shell():
    while True:
        cmd = input(PS.format(computer_name=COMPUTER_NAME, current_dir=os.getcwd()))
        main.interpreter(cmd, COMMANDS)

if __name__ == "__main__":
    try:
        shell()
    except KeyboardInterrupt:
        exit(1)